### ISSUE TITLE
Why is firebase in Groceries.js?

### ISSUE THREAD

**Issue by kevando** [bruz/react-native-redux-groceries#15]
This is an awesome boilerplate, thanks for sharing it! I am confused why the firebase code is in Groceries.js and not separated into an action creator? I am also curious if there is a reason you did not include a `child_changed` listener? 

I am just digging in, so the answer might become obvious soon

**Comment by kevando** [comment]
I ended up adding firebaseRefs to my reducer. Is this bad practice?

```
# reducers/firebase.js
//...
const connectedRef = firebaseApp.database().ref('.info/connected');

const initialState = {
  connectedRef,
}
export default function reducer(state = initialState, action) { ...
```

**Comment by bruz** [comment]
I agree, the Firebase interactions don't belong in the Groceries component. I think I put them there initially for lack of good ideas for where they could go, but it seems like now's a good time to clean that up.

My thought on how to rework it is:
- Add a `src/store/firebase.js` as something that attaches to the store outside of the components, similar to `src/store/syncOffline.js`
  - Create the Firebase refs in there, and attach listeners that dispatch actions on the store
  - Export `itemsRef` so it can be used in actions
- Change the `ADD_ITEM` action so that it just creates the new record in Firebase using the exported `itemsRef`
- Add an action creator for `ADD_ITEM_SUCCESS` that is called from the Firebase event listener so that app state can be updated to include the new item

That seems to separate the responsibilities better to me, but what do you think? I may give this a try sometime in the near future.

Finally, to answer your question about `child_changed`, the app doesn't ever modify existing records, it only creates and destroys them, so it shouldn't even generate that event itself (if I understand Firebase events correctly).

**Comment by kevando** [comment]
Thanks for the thoughtful response! Maintaining boilerplate apps is probably a bitch, so I really appreciate your proactive attitude.
- Adding the firebase code to the store makes total sense, I think I just dont know enough about redux to provide any actionable feedback. 
- I like this approach to ADD_ITEM and this is pretty much what I'm doing.
- Havent dived in enough to encounter this feedback loop yet

You are correct in the way firebase works, but the biggest reason that I like firebase is that if I properly create my data listeners, then I can modify the data from anywhere (ie another user, or some remote server) and the app reflects that change immediately. So yes, I was only able to test `child_changed` by directly manipulating the data in firebase console.

**Comment by milesibastos** [comment]
I think u forgot the file referred by:
`import { syncFirebase } from '../firebase'`

**Comment by bruz** [comment]
@milesibastos oops - thanks for spotting that. I've added it: https://github.com/bruz/react-native-redux-groceries/commit/93667ffc111559fffacc2fa9cd7c184cd52c3406
