### ISSUE TITLE
undefined is not an object (evaluating RCTNetInfo.getCurrentReachability)

### ISSUE THREAD

**Issue by talarari** [bruz/react-native-redux-groceries#3]
https://github.com/facebook/react-native/issues/4047

getting a red screen with an error when loading the app

**Comment by bruz** [comment]
Thanks for catching that. I obviously hadn't tested on Android since adding the NetInfo check. I've got it so it no longer uses that on Android, which just means it won't quickly go into offline mode when there's no connectivity like it does on iOS. It'll show a loading state and wait until Firebase says it's offline, which seems to take a few seconds.

**Comment by bruz** [comment]
Fixed with https://github.com/bruz/react-native-redux-groceries/commit/5c5456254f159489bcca0e26b2e90eafbafab80f
